### ISSUE TITLE
Skyrim SE ERROR: could not find game with APPID '489830'

### ISSUE THREAD

**Issue by Crossfire0mega** [rockerbacon/lutris-skyrimse-installers#254]
I can't get Mod-Organizer 2 to successfully install with the latest release script. After running it I get the following errors. The game runs just fine through steam. 
OS: Debian 11 Stable, KDE Plasma
Nvidia GeForce GTX 1060 Mobile 6GB / Intel Corporation HD Graphics 530
[error.txt](https://github.com/rockerbacon/lutris-skyrimse-installers/files/7532816/error.txt)

**Comment by OlegAckbar** [comment]
I have the same issue

**Comment by SavetheOceans6** [comment]
I am experiencing the same issue when I attempted to install this script as well. This issue has only come about when I attempted re-installation as of today, 11/14/2021.
OS: Mint 20.1, Cinnamon
Nvidia GeForce RTX 2060

**Comment by GenericName987** [comment]
Same problem, reinstalled  multiple times.
OS: Debian Bookworm

**Comment by slaecker** [comment]
Same here with Fallout New Vegas

OS: Arch Linux (fully updated)

# Install log

```
lutris-wrapper: /usr/bin/bash
Started initial process 7682 from /usr/bin/bash -c # clear envs set by Lutris
export LD_LIBRARY_PATH=""

nexus_game_id=newvegas
runner=proton

if [ ! -f "/home/slaecker/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh" ]; then
    "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Could not find gameinfo for '$nexus_game_id', remove Lutris cache and try again"
    exit 1
fi

source "/home/slaecker/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh"

if [ -z "$game_appid" ]; then
    echo "ERROR: empty game_appid" >&2
    exit 1
elif [ -z "$game_steam_subdirectory" ]; then
    echo "ERROR: empty steam_subdirectory" >&2
    exit 1
fi

shared="/home/slaecker/.local/share/modorganizer2"

case "$runner" in
    proton)
        mo2_tricks="vcrun2019"
        mo2_options=""

        if [ -z "$steam_library" ]; then
            steam_library=$("/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh" $game_appid)
        fi

        if [ ! -d "$steam_library" ]; then
            "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
                "Could not find '$game_steam_subdirectory' in your Steam library"
            exit 1
        fi

        game_prefix="$steam_library/steamapps/compatdata/$game_appid/pfx"
        game_installation="$steam_library/steamapps/common/$game_steam_subdirectory"
        game_tricks="$game_protontricks"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options \"\$@\" $game_appid '/home/slaecker/Games/mod-organizer-2_fallout-new-vegas/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/slaecker/Games/mod-organizer-2_fallout-new-vegas/run.sh"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options $game_appid '/home/slaecker/Games/mod-organizer-2_fallout-new-vegas/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/slaecker/Games/mod-organizer-2_fallout-new-vegas/download.sh"
        ;;

    wine)
        mo2_tricks="vcrun2019 dotnet40"
        mo2_options="--proton-wine --winever 5.*"

        "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" warnbox \
            "As of version 5.7, Wine still does not fully support Mod Organizer 2.2.1 and later.\nFor this reason this installer uses the Wine version bundled with Proton 5.0.\nMake sure you have Steam and Proton 5.0 installed on your system"

        game_prefix=$( \
            "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                "Inform the path to your wineprefix" \
        )
        if [ -z "$game_prefix" ]; then
            echo "ERROR: Installation canceled by user" >&2
            exit 1
        fi

        game_tricks="$game_winetricks"

        install_path_candidates=( \
            "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/$game_steam_subdirectory" \
            "$game_prefix/drive_c/GOG Games/$game_steam_subdirectory" \
        )
        if [ -n "$game_gog_subdirectory" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/GOG Games/$game_gog_subdirectory" \
            )
        fi
        if [ "$nexus_game_id" == "fallout3" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/Fallout 3" \
                "$game_prefix/drive_c/GOG Games/Fallout 3" \
            )
        fi

        for path in "${install_path_candidates[@]}"; do
            echo "Searching for game at '$path'"
            if [ -d "$path" ]; then
                echo "Found game"
                game_installation="$path"
                break
            fi
        done

        if [ -z "$game_installation" ]; then
            game_installation=$( \
                "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                    "Could not automatically find the game.\nPlease inform the path where the game is installed" \
            )
            if [ -z "$game_installation" ]; then
                echo "ERROR: installation canceled by user" >&2
                exit 1
            fi
        fi

        # TODO: uncomment once Wine fixes issues with VC2019
        # winever=$( \
        #     "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" textentry \
        #         "Inform which version of Wine you're using\nLeave as * to use the latest version available on Lutris" \
        #         "*" \
        # )
        # if [ -z "$winever" ]; then
        #     echo "ERROR: Installation canceled by user" >&2
        #     exit 1
        # fi

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options \"\$@\" '/home/slaecker/Games/mod-organizer-2_fallout-new-vegas/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/slaecker/Games/mod-organizer-2_fallout-new-vegas/run.sh"

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options '/home/slaecker/Games/mod-organizer-2_fallout-new-vegas/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/slaecker/Games/mod-organizer-2_fallout-new-vegas/download.sh"
        ;;
esac

if [ -d "/home/slaecker/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender" ]; then
    echo "Installing script extender..."

    output=$( \
        cp -af \
        "/home/slaecker/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender/." \
        "$game_installation/" 2>&1 \
    )
    if [ "$?" != "0" ]; then
        "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
            "Error while installing script extender: $output"
        exit 1
    fi
fi

mkdir -p "$game_prefix/drive_c/java"
output=$( \
    cp -af \
    "/home/slaecker/.cache/lutris/installer/mod-organizer-2/extracted-openjdk/." \
    "$game_prefix/drive_c/java/" 2>&1 \
)
if [ "$?" != "0" ]; then
    "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing OpenJDK: $output"
    exit 1
fi

WINEPREFIX="$game_prefix" \
"/home/slaecker/.local/share/lutris/runtime/winetricks/winetricks" -q $mo2_tricks $game_tricks
if [ "$?" != "0" ]; then
    "/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing winetricks, please run Lutris from a terminal and check the logs"
    exit 1
fi

# workaround to stop installation if command fails
echo "success" > '/home/slaecker/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation'
Start monitoring process.
Searching for Steam in '/home/slaecker/.local/share/Steam'
Found Steam
Searching for Steam in '/home/slaecker/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Steam not found in this install path
Searching for game in library '/home/slaecker/.local/share/Steam'
Found game
/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: Zeile 44: return: »Return« ist nur aus einer Funktion oder einem mit »source« ausgeführten Skript möglich.
Searching for game in library '/home/slaecker/.local/share/Steam'
Found game
/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: Zeile 44: return: »Return« ist nur aus einer Funktion oder einem mit »source« ausgeführten Skript möglich.
ERROR: could not find game with APPID '22380'
/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: Zeile 49: return: »Return« ist nur aus einer Funktion oder einem mit »source« ausgeführten Skript möglich.
Searching for Steam in '/home/slaecker/.local/share/Steam'
Found Steam
Searching for Steam in '/home/slaecker/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Steam not found in this install path
Searching for game in library '/home/slaecker/.local/share/Steam'
Searching for game in library '/home/slaecker/.local/share/Steam'
ERROR: could not find game with APPID '22490'
/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: Zeile 49: return: »Return« ist nur aus einer Funktion oder einem mit »source« ausgeführten Skript möglich.
Searching for Steam in '/home/slaecker/.local/share/Steam'
Found Steam
Searching for Steam in '/home/slaecker/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Steam not found in this install path
Searching for game in library '/home/slaecker/.local/share/Steam'
Searching for game in library '/home/slaecker/.local/share/Steam'
ERROR: could not find game with APPID '22490'
/home/slaecker/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: Zeile 49: return: »Return« ist nur aus einer Funktion oder einem mit »source« ausgeführten Skript möglich.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```

# Error popup 1
Could not find 'Fallout New Vegas enplczru' in your Steam library

# Error popup 2
Command exited with code 256

---

I searched the internet and found comments about Lutris not having downloaded winetricks but it's there (also re-installed manually without any change).

```
ls -AHhl /home/slaecker/.local/share/lutris/runtime/winetricks/
total 860K
-rwxrwxr-x 1 slaecker slaecker 859K Nov 21 14:08 winetricks
```

**Comment by itsonlyMiRE** [comment]
same issue here pls someone provide a fix

**Comment by CtrlAltLilith** [comment]
https://github.com/rockerbacon/lutris-skyrimse-installers/pull/256 this should fix it :)

**Comment by SleepingCrows** [comment]
Same issue

> 

i've quite literally tried replacing the variable directories the correct directory and it still doesn't work.

Same deal, Arch Linux, though targeting Fallout 4.

**Comment by CtrlAltLilith** [comment]
@SleepingCrows Did you have an issue trying the patch?

**Comment by SleepingCrows** [comment]
> @SleepingCrows Did you have an issue trying the patch?

Either I'm just incompetent or the patch resulted in the same issue.

Ended up working around it by replacing the script to just send the arbitrary location provided by `compat_data=` and `main_library=` for my environment. 

Even with that resulting in a successful install for proton Fallout 4 in this case, there was other lingering problems with Mod Organizer, the prefix, & it's commands, resulting in poor performance.

I gave up on it already and moved to using Wyre Bash instead.

**Comment by Pritchy96** [comment]
I'm having the same issue with both the latest commit and latest release - also tried the fix under #256, no dice. Tried on both Skyrim SE and Fallout 4, running Arch Linux. Not had a chance to do any sort of a dive yet, log:
[https://pastebin.com/pZq3qPai](Pastebin)

Cheers,
Tom

**Comment by codymikol** [comment]
Troubleshooting this issue myself, it looks like the `grep` in `utils/find-library-for-appid.sh` to get the app from `libraryfolders.vdf` does not work against my file, it returns nothing.

```
"libraryfolders"
{
        "contentstatsid"                "721321942563847283"
        "0"
        {
                "path"          "/home/cody/.local/share/Steam"
                "label"         ""
                "contentid"             "721321942563847283"
                "totalsize"             "0"
                "update_clean_bytes_tally"              "26196374668"
                "time_last_update_corruption"           "0"
                "apps"
                {
                        "440"           "24782365147"
                        "22320"         "1142479546"
                        "105600"                "703963736"
                        "228980"                "273289619"
                        "271590"                "108826526069"
                        "286160"                "3620524310"
                        "292030"                "53483389454"
                        "322330"                "2552256569"
                        "343780"                "53612085"
                        "404790"                "984465948"
                        "413150"                "664445073"
                        "427520"                "1725402857"
                        "504230"                "1201840326"
                        "548430"                "2464537636"
                        "607080"                "32207723456"
                        "632470"                "10068598871"
                        "874260"                "27882886052"
                        "881100"                "1449387275"
                        "892970"                "1156069466"
                        "1097200"               "2257675736"
                        "1145360"               "11892802087"
                        "1150690"               "2041189795"
                        "1167630"               "3287201418"
                        "1391110"               "639290775"
                        "1432860"               "2888536426"
                        "1435790"               "14228324224"
                        "1493710"               "1105007470"
                }
        }
}
```

going to troubleshoot a bit more on this later tonight
